### ISSUE TITLE
npm URL is incorrect

### ISSUE THREAD

**Issue by pmohun** [coldbrewcoders/styled-groove#3]
The readme points to '[...]styled-groovy' instead of '[...]styled-groove'

**Comment by ahnilica** [comment]
Thanks for pointing this typo out. Fixed in commit f332fbd3db34444d326e07eae538d5192f726cd6, will be fixed when merged to master soon.

Also @pmohun, we've just started the the process of revisiting this project. Version 1.0.0 will be launched soon with a lot of improvements, config options and optimizations added. If you're interested in styled-components and this project, we would love to hear your feedback and feature requests.
